class RealESRGanModelsList:
    RealESRGAN_x4plus = 'RealESRGAN_x4plus'
    RealESRNet_x4plus = 'RealESRNet_x4plus'
    RealESRGAN_x4plus_anime_6B = 'RealESRGAN_x4plus_anime_6B'
    RealESRGAN_x2plus = 'RealESRGAN_x2plus'
    RealESRGANv2_anime_xsx2 = 'RealESRGANv2-anime-xsx2'
    RealESRGANv2_animevideo_xsx2_nousm = 'RealESRGANv2-animevideo-xsx2-nousm'
    RealESRGANv2_animevideo_xsx2 = 'RealESRGANv2-animevideo-xsx2'
    RealESRGANv2_anime_xsx4 = 'RealESRGANv2-anime-xsx4'
    RealESRGANv2_animevideo_xsx4_nousm = 'RealESRGANv2-animevideo-xsx4-nousm'
    RealESRGANv2_animevideo_xsx4 = 'RealESRGANv2-animevideo-xsx4'
